package com.myAPI.APIproject.db;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import com.myAPI.APIproject.api.DeleteTaskRequest;
import com.myAPI.APIproject.task.Task;
import com.myAPI.APIproject.user.ToDoAppUser;

@Component
public class TaskDao {
	private Connection conn;
	
	@Autowired
	public TaskDao(Connections connection) {
		super();
		this.conn = connection.init();
	}


	/** method for supervisor to add task to an employee */
	public void assignTask(String taskTitleIn, String taskDescriptionIn, int taskPriorityIn, LocalDate dateIn,
			String userIdIn) {
		Statement stmt = null;
		ResultSet rs = null;
		try {
			stmt = conn.createStatement();
			stmt.executeUpdate("insert into Task (title, description, priority, taskDate, status, userId) values" + "('"
					+ taskTitleIn + "','" + taskDescriptionIn + "','" + taskPriorityIn + "','" + dateIn + "','"
					+ "To Be Completed" + "','" + userIdIn + "');");
		} catch (SQLException ex) {
			System.out.println("SQLException: " + ex.getMessage());
			System.out.println("SQLState: " + ex.getSQLState());
			System.out.println("VendorError: " + ex.getErrorCode());
		} finally {
			if (rs != null) {
				try {
					rs.close();
				} catch (SQLException sqlEx) {
				}
				rs = null;
			}
			if (stmt != null) {
				try {
					stmt.close();
				} catch (SQLException sqlEx) {
				}
				stmt = null;
			}
		}
	}

	/**
	 * method for supervisor to view all tasks generated by entering his name and
	 * password
	 */
	public List<Task> supervisorGetTasks(String empIdIn) {
		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		ToDoAppUser user = (ToDoAppUser) authentication.getPrincipal();
		Statement stmt = null;
		ResultSet rs = null;
		try {
			stmt = conn.createStatement();
			rs = stmt.executeQuery("select id, title, description, priority, taskDate, status from task where userid=\""
					+ empIdIn + "\";");
			List<Task> newList = new ArrayList<>();
			while (rs.next()) {
				int id = rs.getInt("id");
				String title = rs.getString("Title");
				String description = rs.getString("Description");
				int priority = rs.getInt("Priority");
				Date date = rs.getDate("TaskDate");
				LocalDate localDate = date == null ? null : date.toLocalDate();
				String status = rs.getString("Status");
				Task newTask = Task.builder().id(id).title(title).description(description).priority(priority)
						.date(localDate).status(status).build();
				newList.add(newTask);
			}
			return newList;
		} catch (SQLException ex) {
			System.out.println("SQLException: " + ex.getMessage());
			System.out.println("SQLState: " + ex.getSQLState());
			System.out.println("VendorError: " + ex.getErrorCode());
		} finally {
			if (rs != null) {
				try {
					rs.close();
				} catch (SQLException sqlEx) {
				}
				rs = null;
			}
			if (stmt != null) {
				try {
					stmt.close();
				} catch (SQLException sqlEx) {
				}
				stmt = null;
			}
		}
		return null;
	}

	/** method for supervisor to delete task by taskId */
	public void supervisorDeleteTask(String taskIn) {
		Statement stmt = null;
		ResultSet rs = null;
		try {
			stmt = conn.createStatement();
			stmt.executeUpdate("delete from task where id=\"" + taskIn + "\";");
		} catch (SQLException ex) {
			System.out.println("SQLException: " + ex.getMessage());
			System.out.println("SQLState: " + ex.getSQLState());
			System.out.println("VendorError: " + ex.getErrorCode());
		} finally {
			if (rs != null) {
				try {
					rs.close();
				} catch (SQLException sqlEx) {
				}
				rs = null;
			}
			if (stmt != null) {
				try {
					stmt.close();
				} catch (SQLException sqlEx) {
				}
				stmt = null;
			}
		}
	}

	/** method for employee to view all tasks or filter them by priority or date */
	public List<Task> getEmployeeTasksByFilter(String filterIn) {
		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		ToDoAppUser user = (ToDoAppUser) authentication.getPrincipal();
		Statement stmt = null;
		ResultSet rs = null;
		try {
			stmt = conn.createStatement();
			if(filterIn.isEmpty()) {
				rs = stmt.executeQuery("select id, title, description, priority, taskDate, status from task where userid=\""
						+ user.getUserId() + "\";");
			}else {
			rs = stmt.executeQuery("select id, title, description, priority, taskDate, status from task where userid=\""
					+ user.getUserId() + "\" order by " + filterIn + ";");
			}
			List<Task> newList = new ArrayList<>();
			while (rs.next()) {
				int id = rs.getInt("id");
				String title = rs.getString("Title");
				String description = rs.getString("Description");
				int priority = rs.getInt("Priority");
				Date date = rs.getDate("TaskDate");
				LocalDate localDate = date == null ? null : date.toLocalDate();
				String status = rs.getString("Status");
				Task newTask = Task.builder().id(id).title(title).description(description).priority(priority)
						.date(localDate).status(status).build();
				newList.add(newTask);
			}
			return newList;
		} catch (SQLException ex) {
			System.out.println("SQLException: " + ex.getMessage());
			System.out.println("SQLState: " + ex.getSQLState());
			System.out.println("VendorError: " + ex.getErrorCode());
		} finally {
			if (rs != null) {
				try {
					rs.close();
				} catch (SQLException sqlEx) {
				}
				rs = null;
			}
			if (stmt != null) {
				try {
					stmt.close();
				} catch (SQLException sqlEx) {
				}
				stmt = null;
			}
		}
		return null;
	}

	/** method for employee to confirm task completion */
	public void confirmCompletion(String taskIdIn) {
		Statement stmt = null;
		ResultSet rs = null;
		try {
			stmt = conn.createStatement();
			stmt.executeUpdate("update Task set status=\"Completed\" where id=\"" + taskIdIn + "\";");
		} catch (SQLException ex) {
			System.out.println("SQLException: " + ex.getMessage());
			System.out.println("SQLState: " + ex.getSQLState());
			System.out.println("VendorError: " + ex.getErrorCode());
		} finally {
			if (rs != null) {
				try {
					rs.close();
				} catch (SQLException sqlEx) {
				}
				rs = null;
			}
			if (stmt != null) {
				try {
					stmt.close();
				} catch (SQLException sqlEx) {
				}
				stmt = null;
			}
		}
	}
}
